# Generated by Django 4.2.7 on 2024-06-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nombre_demandante', models.CharField(max_length=100)),
                ('dni_demandante', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('presentada', 'Presentada'), ('confirmada', 'Confirmada'), ('sentencia_definitiva', 'Sentencia Definitiva')], default='presentada', max_length=20)),
                ('tipo_delito', models.CharField(choices=[('robo', 'Robo'), ('fraude', 'Fraude'), ('violencia', 'Violencia')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('barrio', models.CharField(choices=[('Agronomía', 'Agronomía'), ('Almagro', 'Almagro'), ('Balvanera', 'Balvanera'), ('Barracas', 'Barracas'), ('Belgrano', 'Belgrano'), ('Caballito', 'Caballito'), ('Chacarita', 'Chacarita'), ('Colegiales', 'Colegiales'), ('Constitución', 'Constitución'), ('Flores', 'Flores'), ('Floresta', 'Floresta'), ('La Boca', 'La Boca'), ('La Paternal', 'La Paternal'), ('Liniers', 'Liniers'), ('Mataderos', 'Mataderos'), ('Monserrat', 'Monserrat'), ('Núñez', 'Núñez'), ('Palermo', 'Palermo'), ('Parque Avellaneda', 'Parque Avellaneda'), ('Parque Chacabuco', 'Parque Chacabuco'), ('Parque Patricios', 'Parque Patricios'), ('Puerto Madero', 'Puerto Madero'), ('Recoleta', 'Recoleta'), ('Retiro', 'Retiro'), ('Saavedra', 'Saavedra'), ('San Cristóbal', 'San Cristóbal'), ('San Nicolás', 'San Nicolás'), ('San Telmo', 'San Telmo'), ('Vélez Sársfield', 'Vélez Sársfield'), ('Villa Crespo', 'Villa Crespo'), ('Villa del Parque', 'Villa del Parque'), ('Villa Devoto', 'Villa Devoto'), ('Villa Lugano', 'Villa Lugano'), ('Villa Luro', 'Villa Luro'), ('Villa Pueyrredón', 'Villa Pueyrredón'), ('Villa Urquiza', 'Villa Urquiza')], max_length=100)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
    ]
